### ISSUE TITLE
Issue with SQLplus and Mac

### ISSUE THREAD

**Issue by martindsouza** [tschf/atom-build-oracle#21]
```
dyld: Library not loaded: /ade/b/2649109290/oracle/sqlplus/lib/libsqlplus.dylib
  Referenced from: /oracle/instantclient_11_2/sqlplus
  Reason: image not found
sed: 1: "/Users/giffy/.atom/pack ...": extra characters at the end of g command
Script took longer than expected
```

This may be the solution: https://blog.caseylucas.com/2013/03/03/oracle-sqlplus-and-instant-client-on-mac-osx-without-dyld_library_path/

**Comment by tschf** [comment]
I was testing this on OS X 10.8. I installed Oracle by downloading
- instant client basic
- sqlplus
- sdk

Unzipped all and placed them at `/bin/oracle/instantclient_11_2`

I put the following in ~/.bash_profile:

```
export PATH=$PATH:/bin/oracle/instantclient_11_2:/bin/oracle/sqlcl/bin
export DYLD_LIBRARY_PATH=/bin/oracle/instantclient_11_2:$DYLD_LIBRARY_PATH
```

..

And, didn't experience the library not loaded error.
The sed error is probably related to #20

**Comment by tschf** [comment]
Looks like DYLD_LIBRARY_PATH isn't making it into Atom. I saw this related issue on another project: https://github.com/JunoLab/atom-julia-client/issues/67 , specific to El Capitan.

There is another technique to update the linked library paths, but it requires a command called `otool`, which is only available if you have Xcode installed for usage. See: https://blog.caseylucas.com/2013/03/03/oracle-sqlplus-and-instant-client-on-mac-osx-without-dyld_library_path/

**Comment by tschf** [comment]
Reading this document: https://blogs.oracle.com/taylor22/entry/sqlplus_and_dyld_library_path, there is the suggestion of an alias. This works well in the terminal, but in Atom, it falls back to the raw command thus bringing back the error.

If you look at this document: http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html, part of the instructions are to create a `lib` folder in your home directory which a bunch of symlinks. That also seems to resolve the issue.

```
sudo ln -s /opt/Oracle/instantclient_11_2/libclntsh.dylib.11.1 /usr/lib/libclntsh.dylib.11.1
sudo ln -s /opt/Oracle/instantclient_11_2/libnnz11.dylib /usr/lib/libnnz11.dylib
sudo ln -s /opt/Oracle/instantclient_11_2/libociei.dylib ~/lib/libociei.dylib
#And, again for some SQL*Plus libs.
sudo ln -s /opt/Oracle/instantclient_11_2/libsqlplus.dylib ~/lib/libsqlplus.dylib
sudo ln -s /opt/Oracle/instantclient_11_2/libsqlplusic.dylib ~/lib/libsqlplusic.dylib
```

Note, I tried pointing to /usr/lib/\* but seemed to get an operation not permitted message, even as sudo (Seemingly a feature known as [System Integrity Protection](http://apple.stackexchange.com/questions/208764/cant-write-to-usr-lib)).

..

Update: Just tried pointing to /usr/local/lib and that seems also fine - I feel this is better to not fill up your home dir with libs.

**Comment by tschf** [comment]
Another approach I could take is to add a setting for DYLD_LIBRARY_PATH, only visible on OS X, that would allow the user to set in directly in the configuration, and then add it to the environment.. `process.env.DYLD_LIBRARY_OPATH=getSetting()`.
