### ISSUE TITLE
Unable to ope file .../build-oracle.sql on windows 10

### ISSUE THREAD

**Issue by jiri-kajaba** [tschf/atom-build-oracle#23]
![oracle-build-error](https://cloud.githubusercontent.com/assets/19873641/15985258/bad52b4a-2fe7-11e6-8c1f-a456291a5bd5.png)

**Comment by tschf** [comment]
Thanks for the report. I introduced some logic specific to *nix based systems, which passes the package dir to the script. Specifically: https://github.com/tschf/atom-build-oracle/blob/master/lib/make.js#L58 - the array (`thisConfig.args`) shouldn't have this element on Windows (it has no need for it).

I won't get to this for a couple of weeks.

**Comment by vincentmorneau** [comment]
+1 on this issue.

**Comment by tschf** [comment]
Thanks for bumping this and bringing it back on my radar. I just got home yesterday afternoon - will aim to check this out this afternoon (sorry for the delay).
