### ISSUE TITLE
Build never stops

### ISSUE THREAD

**Issue by vincentmorneau** [tschf/atom-build-oracle#24]
May be related to #23.

I have made a modification to https://github.com/tschf/atom-build-oracle/blob/master/lib/make.js#L58
so it compiles on Windows. It is now:

```
"", // pkgDir
```

Now I am able to run both sqlplus and sqlcl, nice!

But it appears like the build runs endlessly:

![image](https://cloud.githubusercontent.com/assets/5391291/16629034/39bdb622-4382-11e6-8aec-d1ed22051caa.png)

Unless a do a `Build: Stop` manually. Weird because the result set is returned pretty quickly.

**Comment by tschf** [comment]
Looks like the SQL (compilation) script isn't exiting. Is this with both sqlcl/sqlplus?

**Comment by vincentmorneau** [comment]
Yes, both.

**Comment by vincentmorneau** [comment]
That worked, thanks!
