### ISSUE TITLE
Can't compile when path to script contains a space

### ISSUE THREAD

**Issue by vincentmorneau** [tschf/atom-build-oracle#25]
When the root directory contains a space, the compilation won't work (on Windows at least):

![image](https://cloud.githubusercontent.com/assets/5391291/16658838/d5058980-4435-11e6-93ac-5b4b6cd290f3.png)

Executing the same script with no space in the root directory runs great:

![image](https://cloud.githubusercontent.com/assets/5391291/16658855/f55734c2-4435-11e6-90d8-3cafc7787aae.png)

**Comment by tschf** [comment]
Thanks for catching that. Wrapping the call to the desired file in the SQL script in quotes now.
