### ISSUE TITLE
Charset issue

### ISSUE THREAD

**Issue by vincentmorneau** [tschf/atom-build-oracle#29]
Not sure if this is related to `atom-build-oracle`, but I am having a character set issue.

When writing french accents in Atom (UTF-8):

![image](https://cloud.githubusercontent.com/assets/5391291/17034392/86ecd20a-4f50-11e6-8e96-9901e61c49e1.png)

It gets changed in the database. SQL developer is also set to UTF-8.

![image](https://cloud.githubusercontent.com/assets/5391291/17034466/c9cd6922-4f50-11e6-9854-5b829b11e066.png)

Database itself is also set to UTF-8:

![image](https://cloud.githubusercontent.com/assets/5391291/17034553/2b748192-4f51-11e6-8416-48d6ab1a41eb.png)

Any thoughts?

**Comment by tschf** [comment]
Do you get the same if you compile the file directly in SqlPlus/SQLcl, from command prompt?
Do you have NLS_LANG environment var set?

This [post](http://dba.stackexchange.com/questions/7765/determine-oracle-session-client-character-set) suggests you can query `v$session_connect_info` to find out what is being used.

Haven't tested yet, just a couple of thoughts in the meantime.

**Comment by vincentmorneau** [comment]
It works well when compiling directly from SQLcl (command prompt).

I could not find anything useful with `v$session_connect_info`, but I ran the following in both Atom (SQLcl) and Command Prompt (SQLcl):

```
select * from v$nls_parameters
where parameter = 'NLS_CHARACTERSET'
;
```

and got the same result:

```
PARAMETER                                                        VALUE
---------------------------------------------------------------- ----------------------------------------------------------------
NLS_CHARACTERSET                                                 AL32UTF8
```

One character that fails is `é`, you can try with:

```
create or replace package nls_test
is
    dummy number; -- éééééé
end nls_test;
/
```

---

Furthermore, it works from Atom when using `Windows 1252` instead of "UTF-8". Weird.

![image](https://cloud.githubusercontent.com/assets/5391291/17059478/5fd38684-4ff3-11e6-9a71-7d4a8d8a905e.png)

**Comment by tschf** [comment]
When querying that view `v$session_connect_info`, I can see that SQL*Plus sets the client charset to `US7ASCII`, whereas SQLcl and SQL Dev has it as `Unknown`. I had a look at the statements window in SQL Dev to see if anything is set as far as encoding is concerned, but there doesn't appear to be. 

On the command line, if I do: `export NLS_LANG=.AL32UTF8` before connecting to SQL*Plus, the compilation succeeds (as in, accented character persists). Proposed solution is a new configuration item for NLS_LANG, with a default value of `AL32UTF8`. Set that variable only if there isn't a current environment variable for that.

**Comment by vincentmorneau** [comment]
Thanks Trent. Now it works in SQL*Plus but still not in SQLcl.

**Comment by tschf** [comment]
Oh yes, I tested SQLcl in my system and it worked. Just tested in Windows and see the issue still there.

**Comment by tschf** [comment]
I pinged the team on [Twitter](https://twitter.com/trentschafer/status/759147289940103168), as I'm not quite sure how to resolve this.

![screenshot from 2016-07-30 07-31-49](https://cloud.githubusercontent.com/assets/1747643/17264742/609711d2-562c-11e6-9984-8632a719da9a.png)

Also found this thread https://community.oracle.com/thread/3923443?start=0&tstart=0, which suggests it should just work without setting anything.

**Comment by vincentmorneau** [comment]
Do you think [this](https://twitter.com/trentschafer/status/769150907418222592) is doable within `atom-build-oracle`?

**Comment by tschf** [comment]
Yeah, I think it should be. Need to get in there and give it a better test, and think of the best way to add it in (through a config or just do it always by default). Will try get onto this next week (if not before).

**Comment by tschf** [comment]
@vincentmorneau Did you want to give that a test? It seemed to be working, but thought better get a second test before closing.

**Comment by vincentmorneau** [comment]
Works perfectly. This tool is great! Thanks Trent.
