### ISSUE TITLE
Running files on relative paths

### ISSUE THREAD

**Issue by vincentmorneau** [tschf/atom-build-oracle#30]
My structure looks like:
- [root]
  - .atom-build-oracle.json
  - [packages]
    - vd_utils.pks
    - vd_utils.pkb
  - [release]
    - release.sql

The **release** contains `release.sql` which calls something in the **packages** folder:

``` sql
prompt PACKAGES
@..\packages\vd_util.pks
@..\packages\vd_util.pkb
```

Result is:

```
SP2-0310: unable to open file "..\packages\vd_util.pks"
SP2-0310: unable to open file "..\packages\vd_util.pkb"
```

So it appears that any script `atom-build-oracle` runs is treated like it's on the **root** folder, so we can't use relative paths.

---

Test case: the following code works (as if release.sql is in the **root** folder).

``` sql
prompt PACKAGES
@packages\vd_util.pks
@packages\vd_util.pkb
```

**Comment by vincentmorneau** [comment]
I should mention that this occurs with both SQLPlus and SQLcl.

**Comment by tschf** [comment]
I think this should resolve if I cd into the directory of the file you are running - will give it a test soon.

Btw, thanks for all the bug reports! Will hopefully publish soon.
