### ISSUE TITLE
Missing Settings button

### ISSUE THREAD

**Issue by martindsouza** [tschf/atom-build-oracle#31]
The documentation screenshots reference a the `Settings` for this package. There is no settings button for this package.

![image](https://cloud.githubusercontent.com/assets/2925726/17382625/08396ee8-598f-11e6-92f1-fbad47b868f7.png)

**Comment by tschf** [comment]
Just tried reproducing this, and I found that after I install the package
the settings button isn't there. But when I restart or reload Atom, the
settings button appears.

**Comment by tschf** [comment]
Also, you should be able to click anywhere on the card to open the package info/settings page

**Comment by martindsouza** [comment]
Turns out I had an older version of Atom. I was running `1.8.0`. Now updated to `1.9.2` and it works.
