### ISSUE TITLE
Support for multiple connection strings

### ISSUE THREAD

**Issue by vincentmorneau** [tschf/atom-build-oracle#36]
Idea for an upcoming version: supporting multiple connection strings. If multiple connection strings are available, user would have to choose which one to use.

**.atom-build-oracle.json** example:

``` json
[
    {
        "targetName" : "hr: dev",
        "connectString" : "hr/hr@XE1"
    },
    {
        "targetName" : "hr: test",
        "connectString" : "hr/hr@XE2"
    }
]
```

Thoughts?

**Comment by tschf** [comment]
This should already be supporting this. Always, when you start Atom, it selects the first target. When you change targets, that remains the active target until you switch again

In the bottom left, you should see the target name which you can click to change to the active target:

![image](https://cloud.githubusercontent.com/assets/1747643/18183929/f4794b00-70d9-11e6-858c-2f8922dbd217.png)

![image](https://cloud.githubusercontent.com/assets/1747643/18183949/04f508a2-70da-11e6-89c1-d683291f6cce.png)

Also, f7 / ctrl+alt+t allows you to choose which target to build.

Is this working for you?

**Comment by vincentmorneau** [comment]
My bad. Thanks.

**Comment by tschf** [comment]
That's cool :-)
