### ISSUE TITLE
Compiling views errors

### ISSUE THREAD

**Issue by vincentmorneau** [tschf/atom-build-oracle#39]
This fails
* `/*+ materialize */` hint
* empty line between `from` and `join`
```sql
create or replace force view vincent as
with something as (
    select /*+ materialize */ 1 id
    from dual
)
select 1 id
from dual d

join something s
on 1 = 1;
```

This works
* NO `/*+ materialize */` hint
* empty line between `from` and `join`
```sql
create or replace force view vincent as
with something as (
    select 1 id
    from dual
)
select 1 id
from dual d

join something s
on 1 = 1;
```

This works
* `/*+ materialize */` hint
* NO empty line between `from` and `join`
```sql
create or replace force view vincent as
with something as (
    select /*+ materialize */ 1 id
    from dual
)
select 1 id
from dual d
join something s
on 1 = 1;
```

Somehow the combination of the hint and the empty line fails the compilation.

**Comment by tschf** [comment]
I seemingly forgot to publish a new version after fixing #35.

Tested with your first example after publishing new version (1.5.2), and it seems to be good now.
Although, in your second example, that didn't work for me before this change - can you give this a test and let me know if it's all good now?

![image](https://cloud.githubusercontent.com/assets/1747643/23145325/95a898d6-f821-11e6-8849-761c5ca9a396.png)

**Comment by vincentmorneau** [comment]
It's working now. Weird that example 2 worked for me before though.

Thanks!
