### ISSUE TITLE
Help Setup SQLPLUS Oracle XE

### ISSUE THREAD

**Issue by DevDorrejo** [tschf/atom-build-oracle#40]
Hello, i Need help in setup this package to Oracle-Xe, but i am new working with database, that some options like needed i can not successfully fill with the correct params.

**Comment by vincentmorneau** [comment]
@Akumetsu-Dev have you installed atom-build-oracle through Atom?

**Comment by DevDorrejo** [comment]
yes

**Comment by tschf** [comment]
You may want to give some more information? 

You've got XE up and running? You can connect to the database with SQL Plus on the command line? You've set up the build configuration file as described in the README? 

Please provide an example where you can connect the database with sqlplus from the command prompt but are unable to do so with Atom to compile your code.

**Comment by tschf** [comment]
Closing this due to no additional information in approaching 6 months.
