### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by Elivilson** [tschf/atom-build-oracle#41]
### Steps to reproduce:

1. Open a new file and keep it untitled;
2. Put inside of it a valid plsql statement;
3. Build.

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [build-oracle](https://github.com/tschf/atom-build-oracle) package 1.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At ~\.atom\packages\build-oracle\lib\make.js:104

TypeError: Cannot read property 'path' of null
    at doMatch (/packages/build-oracle/lib/make.js:104:83)
    at /packages/build/lib/error-matcher.js:74:52
    at Array.forEach (native)
    at ErrorMatcher._parse (/packages/build/lib/error-matcher.js:73:38)
    at ErrorMatcher.set (/packages/build/lib/error-matcher.js:131:10)
    at /packages/build/lib/build.js:189:27)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (/packages/build/node_modules/cross-spawn/lib/enoent.js:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:55.7.0 core:copy (input.hidden-input)
     -0:55.3.0 application:new-file (input.hidden-input)
     -0:54.7.0 core:paste (input.hidden-input)
     -0:44.7.0 grammar-selector:show (input.hidden-input)
     -0:42.5.0 core:confirm (input.hidden-input)
     -0:41.3.0 build:select-active-target (input.hidden-input)
     -0:00.9.0 build:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-abl 0.1.2 
autocomplete-oracle 0.4.0 
build 0.67.0 
build-cmd 0.5.0 
build-oracle 1.5.2 
busy 0.7.0 
ex-mode 0.13.1 
highlight-selected 0.12.0 
language-abap 1.1.0 
language-abl 0.10.1 
language-batchfile 0.5.2 
language-oracle 1.6.2 
linter 1.11.23 
linter-bootlint 1.0.4 
linter-javac 1.9.4 
linter-jshint 3.0.2 
linter-jsonlint 1.3.0 
linter-pylint 1.2.2 
minimap 4.26.8 
minimap-linter 1.6.0 
open-recent 5.0.0 
scroll-sync 0.1.5 
sort-lines 0.14.0 
split-diff 1.2.0 
tab-title 0.3.3 
vim-mode-plus 0.82.3 
vim-mode-plus-ex-mode 0.8.1 
word-jumper 0.3.0 
xml-formatter 0.10.0 
```

**Comment by LilyAventureira** [comment]
Perhaps it could check if the file is untitled, save a temporary file with the content in the editor, and build it as usual.

**Comment by tschf** [comment]
Thanks for the feedback. I kinda figured people would be compiling saved files, but looks like I hadn't built in checks to enforce that.

I've just added in an implementation to work on untitled files. One hiccup is with the error matching functionality. One of the required attributes is the file that the error occured in (which I typically just point to the active file). 

(
side note: this is the functionality that shows when errors have occured in the compilation:
![image](https://cloud.githubusercontent.com/assets/1747643/23592097/f37cb19e-024f-11e7-8e30-dc64b06ed659.png)
)

So, either I can skip the error matching checks on untitled files - and you can just visually inspect the output; or point to the temporary file. With the latter case, this results in two files being opened.

As an example, this happens:

![image](https://cloud.githubusercontent.com/assets/1747643/23592115/11e2df28-0250-11e7-89ed-4030e8ac3c62.png)

I feel both cases aren't ideal (1. creates two identical files in the atom workspace; 2. misses the visual feedback that there are errors in the script).

Welcome any input.

**Comment by vincentmorneau** [comment]
My two cents: I don't see the added value in this. `atom-build-oracle` is useful for building saved files which are under version control (eliminates back and forth between the code editor and the compiler).

If I have to run unsaved queries against the DB, SQL Dev is right there, and it will always be more robust for messing around in a worksheet.

**Comment by LilyAventureira** [comment]
@tschf 
> I feel both cases aren't ideal (1. creates two identical files in the atom workspace; 2. misses the visual feedback that there are errors in the script).

I agree that both cases aren't ideal, but we may be able to work with the first case. If you can close the untitled editor, there's really no difference for the user between having a untitled tab or a temporary file.

@vincentmorneau 
> If I have to run unsaved queries against the DB, SQL Dev is right there, and it will always be more robust for messing around in a worksheet.

That's true. I myself usually build saved files. However, since `atom-build-oracle`'s premise is to run the active file in the editor, I see it as a valid use case.

At the time I opened this issue, I was just trying to to check a single row of a table with a small select, and I didn't feel like opening SQL Dev for it since Atom was open, and `atom-build-oracle` already gives it access to sql*plus.

**Comment by tschf** [comment]
Appreciate both perspectives. 

Still, being able to compile an unsaved file surely can't hurt. 

Another snag I noticed is that you can only compile files that belong in the project path (e.g. it doesn't pick up the build configuration when opening a file from /tmp). 

Ok, so here's what I've done. When compiling, in the preBuild phase I create a temporary file with the untitled files contents'. Obviously, then point the build configuration to that temporary file (I unset the current working directory (usually it's the path to of the file being run) - I could set that to the root project path). 

I prepend this file with the following string:

> -- This file was auto generated on \<DATE\> by
-- the `build-oracle` Atom plugin as the plugin requires a saved file to 
-- compile and report any compilation errors. 
-- 
-- This file will be discarded upon exit from Atom; If you want to keep the 
-- script you should save the file somewhere more practical.

The only time the file is opened if you click the issues message in the status bar:

![image](https://cloud.githubusercontent.com/assets/1747643/23736784/8e6e04f2-04e2-11e7-95e3-111697f9e010.png)

![image](https://cloud.githubusercontent.com/assets/1747643/23736792/a1e62e42-04e2-11e7-8f16-976d12745fc8.png)

Trying to compile this file, will result in this alert:

![image](https://cloud.githubusercontent.com/assets/1747643/23736846/ef99fd44-04e2-11e7-8d4e-79ede0e39fa6.png)

I could create the temporary file within the opened project path. I'm a bit reluctant to do this as it could create a false sense of security (that the files will still be there when you re-launch the project).

..

Ok, so this code is currently in the branch "tschf/41". If you/anyone would like to test this to offer critisicms, you can follow these general steps:

```bash
trent@birroth:~$ rm -f ~/.atom/dev/packages/build-oracle #Clean build-oracle dev package
trent@birroth:~$ echo $ATOM_REPOS_HOME #This is where atom dev packages get cloned to or look for packages
/home/trent/Projects/
trent@birroth:~$ cd /home/trent/Projects/
trent@birroth:~/Projects$ git clone https://github.com/tschf/atom-build-oracle.git -b tschf/41 build-oracle #Folder name needs to match Atom package name
Cloning into 'build-oracle'...
remote: Counting objects: 408, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 408 (delta 6), reused 0 (delta 0), pack-reused 392
Receiving objects: 100% (408/408), 67.02 KiB | 91.00 KiB/s, done.
Resolving deltas: 100% (225/225), done.
Checking connectivity... done.
trent@birroth:~/Projects$ apm dev build-oracle # Create a link to the package just cloned
/home/trent/.atom/dev/packages/build-oracle -> /home/trent/Projects/build-oracle
trent@birroth:~/Projects/build-oracle$ cd ~/.atom/dev/packages/build-oracle
trent@birroth:~/.atom/dev/packages/build-oracle$ apm i #install dependencies
Installing modules ✓
trent@birroth:~/.atom/dev/packages/build-oracle$ cd ~/Projects/PureMigration/
trent@birroth:~/Projects/PureMigration$ atom -d . #Launch atom in dev mode to load dev packages
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

Not tested on Windows.

I'll look to merge this sometime in the next week if all looks good.
